<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseAppHost>true</UseAppHost>
    <Nullable>enable</Nullable>
    <AssemblyName>osu-stable-to-lazer</AssemblyName>
    <RootNamespace>OsuStableToLazer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ppy.osu.Game" Version="2026.730.0" />
    <PackageReference Include="ppy.osu.Game.Rulesets.Osu" Version="2026.730.0" />
    <PackageReference Include="ppy.osu.Game.Rulesets.Catch" Version="2026.730.0" />
    <PackageReference Include="ppy.osu.Game.Rulesets.Taiko" Version="2026.730.0" />
    <PackageReference Include="ppy.osu.Game.Rulesets.Mania" Version="2026.730.0" />
  </ItemGroup>
</Project>

